#!/bin/sh

wd=$(pwd)
runningDir="$(dirname "$(readlink -f "$0")")"
if [ ! -d "$runningDir/node_modules" ]; then 
    echo "Dependencies not installed!"
    read -p "Install now? (y/n): " response
    if [ ${response,,} = "y" ]; then
        cd $runningDir
        npm install
        cd $wd
    else
        echo "The program cannot be run with missing dependencies. Exiting."
        exit 1
    fi        
fi

node "$runningDir/index.js"
